version: "3.9"

services:

    nginx:
        image: nginx:latest
        container_name: apicomm_nginx
        restart: unless-stopped
        volumes:
            -   ./_docker/nginx/logs:/var/log/nginx
            -   ./:/var/www
            -   ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            -   "80:80"
        depends_on:
            -   app
            -   db
        networks:
            -   apicomm

    app:
        build:
            context: .
            dockerfile: ./_docker/php/Dockerfile
        restart: unless-stopped
        container_name: apicomm_app
        working_dir: /var/www
        volumes:
            -   ./_docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            -   ./:/var/www/
            -   ./_docker/php/start.sh:/usr/local/bin/start.sh
        networks:
            -   apicomm
        depends_on:
            -   db

    db:
        image: postgres:16
        restart: unless-stopped
        container_name: apicomm_postgresql
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: apicomm
        volumes:
            -   apicomm_pg_data:/var/lib/postgresql/data
        ports:
            -   "5432:5432"
        networks:
            -   apicomm

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: apicomm_pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin123
        ports:
            -   "5050:80"
        volumes:
            -   apicomm_pgadmin_data:/var/lib/pgadmin
        depends_on:
            -   db
        networks:
            -   apicomm


    node:
        build:
            context: .
            dockerfile: ./_docker/nodejs/Dockerfile
        container_name: apicomm_node
        restart: unless-stopped
        tty: true
        ports:
            -   "5173:5173"
        working_dir: /var/www
        volumes:
            -   .:/var/www
        networks:
            -   apicomm

volumes:
    apicomm_pg_data:
    apicomm_pgadmin_data:
    apicomm_redis_data:

networks:
    apicomm:

